<a href="https://colab.research.google.com/github/plaban1981/INEURON/blob/master/Ineuron_assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Task 1:
- 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [11]:
def divide(a,b):
  return a/b
try:
  numerator = int(input('Enter the value of the numerator'))
  denominator = int(input('Enter the value of the denominator'))
  result = divide(numerator,denominator)
  print(f'division of {numerator} / {denominator} = {result}')
except (Exception,ZeroDivisionError) as e:
  print(f" {e} error - Please eneter a non zero denominator")

Enter the value of the numerator5
Enter the value of the denominator0
 division by zero error - Please eneter a non zero denominator


## 2.Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

####Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]


#### Output should come as below:
Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.

In [1]:
subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]

for subject in subjects:
  for verb in verbs:
    for obj in objects:
      print( subject + " " + verb + " " + obj)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


##Task 2:
#### 1.Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

#### HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde

In [0]:
def atv(list_element,nthpower):   
  X = []
  for num in list_element:
    for i in range(1,nthpower+1):
      X.append(num ** i)
  return np.array(X).reshape(len(list_element),n)


In [29]:
import numpy as np
n=4
list_element = [1,2,3,4,5]
elements = len(list_element)
result = np.array(atv(list_element,n))
print(result)

[[  1   1   1   1]
 [  2   4   8  16]
 [  3   9  27  81]
 [  4  16  64 256]
 [  5  25 125 625]]
