<a href="https://colab.research.google.com/github/plaban1981/INEURON/blob/master/Ineuron_Sunday_12_01_2020_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy base of all advanced libraries

In [0]:
import numpy as np


In [2]:
lst =[1,2,3,4,6]
arr1 = np.array(lst)
arr1.shape

(5,)

In [3]:
lst =[[1,2,3],[4,5,6]]
arr1 = np.array(lst)
arr1.shape

(2, 3)

In [4]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
lst1 = [1,'hi']
np.array(lst1)

array(['1', 'hi'], dtype='<U21')

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## select random values from uniform distribution between 0 and 1

In [12]:
np.random.rand(2)# select 2 random values

array([0.59131291, 0.44493748])

In [13]:
np.random.randint(10,20,5)

array([12, 12, 16, 15, 17])

##return index position of max element in the list

In [14]:
np.argmax(lst)

5

In [17]:
np.random.randint(1,2,0)

array([], dtype=int64)

In [18]:
np.random.randn(5)# select values from standard normal distribution

array([-0.75498721,  2.69732496,  1.83270952,  0.03737953,  0.72062806])

In [22]:
np.vander([1,2,3,4])

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [23]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

## Universal array function

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [28]:
np.sort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [30]:
np.where(arr > 4)

(array([5, 6, 7, 8, 9]),)

In [31]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
np.sort(arr)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [34]:
arr3 = np.array(([5,10,15],[10,20,20],[15,16,17]))
arr3

array([[ 5, 10, 15],
       [10, 20, 20],
       [15, 16, 17]])

In [37]:
arr3.shape

(3, 3)

In [38]:
arr3[::2,::2]

array([[ 5, 15],
       [15, 17]])

In [41]:
arr3[:2,:3]

array([[ 5, 10, 15],
       [10, 20, 20]])

In [42]:
arr3[:2,::2]

array([[ 5, 15],
       [10, 20]])

In [44]:
arr3[:2,::1]

array([[ 5, 10, 15],
       [10, 20, 20]])