<a href="https://colab.research.google.com/github/plaban1981/INEURON/blob/master/Pandas_1_29JanClass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# read and write using pandas

In [0]:
import os

In [0]:
# get the current working directory
os.getcwd()

'D:\\datascience\\acad\\acad material\\Session-IPYNB 11'

In [0]:
#change current working directory
os.chdir('D:\\datascience\\acad\\acad material\\Session-IPYNB 11')

In [0]:
os.getcwd()

'D:\\datascience\\acad\\acad material\\Session-IPYNB 11'

In [0]:
# list down all objects in the current working directory
os.listdir('D:\\datascience\\acad\\acad material\\Session-IPYNB 11')

['.ipynb_checkpoints', 'College_Data.npy', 'Numpy_1.ipynb', 'Python_5.ipynb']

In [0]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t') 

In [4]:
type(titanic_train)

pandas.core.frame.DataFrame

In [5]:
titanic_train.head(1)

PassengerId  Survived  Pclass  ...  Fare Cabin  Embarked
0            1         0       3  ...  7.25   NaN         S

[1 rows x 12 columns]

In [6]:
titanic_train.tail()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
151          152         1       1  ...  66.6000    C2         S
152          153         0       3  ...   8.0500   NaN         S
153          154         0       3  ...  14.5000   NaN         S
154          155         0       3  ...   7.3125   NaN         S
155          156         0       1  ...  61.3792   NaN         C

[5 rows x 12 columns]

In [7]:
titanic_train.shape

(156, 12)

In [8]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [0]:
print( titanic_train.describe() )

       PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000  


In [0]:
pd.pandas.set_option('display.max_columns',None)

In [10]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [12]:
pd.get_dummies(titanic_train['Embarked']).head()#one-hot encoding

C  Q  S
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1

In [15]:
pd.get_dummies(titanic_train['Embarked'],drop_first=True).head()# Dummy Coding, drop first referrence

Q  S
0  0  1
1  0  0
2  0  1
3  0  1
4  0  1

In [16]:
cat_cols = [col for col in titanic_train.columns if titanic_train[col].dtype == 'object']
cat_cols

['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [18]:
titanic_train.describe(include='O')

Name   Sex  Ticket        Cabin Embarked
count                                 156   156     156           31      155
unique                                156     2     145           28        3
top     Pears, Mrs. Thomas (Edith Wearne)  male  347082  C23 C25 C27        S
freq                                    1   100       2            2      110

In [17]:
categorical = titanic_train.dtypes[titanic_train.dtypes == "object"].index
print(categorical)

titanic_train[categorical].describe()

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')


Name   Sex  Ticket        Cabin Embarked
count                                 156   156     156           31      155
unique                                156     2     145           28        3
top     Pears, Mrs. Thomas (Edith Wearne)  male  347082  C23 C25 C27        S
freq                                    1   100       2            2      110

In [19]:
len(titanic_train["PassengerId"])

156

In [0]:
del titanic_train["PassengerId"]     # Remove PassengerId

In [21]:
sorted(titanic_train["Name"])[0:15]   # Check the first 15 sorted names

['Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Allen, Mr. William Henry',
 'Andersson, Miss. Ellis Anna Maria',
 'Andersson, Miss. Erna Alexandra',
 'Andersson, Mr. Anders Johan',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andreasson, Mr. Paul Edvin',
 'Andrew, Mr. Edgardo Samuel',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Attalah, Miss. Malake',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Barton, Mr. David John',
 'Bateman, Rev. Robert James',
 'Baxter, Mr. Quigg Edmond']

In [22]:
sorted(titanic_train["Name"])[0:15]

['Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Allen, Mr. William Henry',
 'Andersson, Miss. Ellis Anna Maria',
 'Andersson, Miss. Erna Alexandra',
 'Andersson, Mr. Anders Johan',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andreasson, Mr. Paul Edvin',
 'Andrew, Mr. Edgardo Samuel',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Attalah, Miss. Malake',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Barton, Mr. David John',
 'Bateman, Rev. Robert James',
 'Baxter, Mr. Quigg Edmond']

In [23]:
titanic_train["Name"].describe()

count                                   156
unique                                  156
top       Pears, Mrs. Thomas (Edith Wearne)
freq                                      1
Name: Name, dtype: object

In [24]:
titanic_train["Ticket"][0:15]       # Check the first 15 tickets

0            A/5 21171
1             PC 17599
2     STON/O2. 3101282
3               113803
4               373450
5               330877
6                17463
7               349909
8               347742
9               237736
10             PP 9549
11              113783
12           A/5. 2151
13              347082
14              350406
Name: Ticket, dtype: object

In [26]:
titanic_train["Ticket"].describe()

count        156
unique       145
top       347082
freq           2
Name: Ticket, dtype: object

In [0]:
del titanic_train["Ticket"]        # Remove Ticket

In [28]:
titanic_train["Cabin"][0:15]       # Check the first 15 tickets

0      NaN
1      C85
2      NaN
3     C123
4      NaN
5      NaN
6      E46
7      NaN
8      NaN
9      NaN
10      G6
11    C103
12     NaN
13     NaN
14     NaN
Name: Cabin, dtype: object

In [29]:
titanic_train["Cabin"].describe()  # Check number of unique cabins

count              31
unique             28
top       C23 C25 C27
freq                2
Name: Cabin, dtype: object

In [30]:
new_survived = pd.Categorical(titanic_train["Survived"])
print(new_survived)
new_survived = new_survived.rename_categories(["Died","Survived"])              

new_survived.describe()

[0, 1, 1, 1, 0, ..., 1, 0, 0, 0, 0]
Length: 156
Categories (2, int64): [0, 1]


counts     freqs
categories                  
Died           102  0.653846
Survived        54  0.346154

In [31]:
titanic_train['Survived'].value_counts()

0    102
1     54
Name: Survived, dtype: int64

In [32]:
new_Pclass = pd.Categorical(titanic_train["Pclass"],ordered=True)
print(titanic_train["Pclass"].value_counts())
print(new_Pclass)
new_Pclass = new_Pclass.rename_categories(["Class1","Class2","Class3"])     
new_Pclass.describe()

3    96
2    30
1    30
Name: Pclass, dtype: int64
[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1 < 2 < 3]


counts     freqs
categories                  
Class1          30  0.192308
Class2          30  0.192308
Class3          96  0.615385

In [33]:
titanic_train["Pclass"].nunique()

3

In [35]:
titanic_train["Pclass"].unique()

array([3, 1, 2])

In [0]:
titanic_train["Pclass"] = new_Pclass

In [37]:
titanic_train.head()

Survived  Pclass                                               Name  \
0         0  Class3                            Braund, Mr. Owen Harris   
1         1  Class1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1  Class3                             Heikkinen, Miss. Laina   
3         1  Class1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0  Class3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch     Fare Cabin Embarked  
0    male  22.0      1      0   7.2500   NaN        S  
1  female  38.0      1      0  71.2833   C85        C  
2  female  26.0      0      0   7.9250   NaN        S  
3  female  35.0      1      0  53.1000  C123        S  
4    male  35.0      0      0   8.0500   NaN        S

In [38]:
titanic_train["Cabin"].unique()   # Check unique cabins

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [39]:
char_cabin = titanic_train["Cabin"].astype(str) # Convert data to str
char_cabin


0       nan
1       C85
2       nan
3      C123
4       nan
       ... 
151      C2
152     nan
153     nan
154     nan
155     nan
Name: Cabin, Length: 156, dtype: object

In [40]:
new_Cabin = np.array([cabin[0] for cabin in char_cabin]) # Take first letter

new_Cabin = pd.Categorical(new_Cabin)

new_Cabin .describe()

counts     freqs
categories                  
A                2  0.012821
B                5  0.032051
C               10  0.064103
D                6  0.038462
E                3  0.019231
F                4  0.025641
G                1  0.006410
n              125  0.801282

In [0]:
titanic_train["Cabin"] = new_Cabin

In [42]:
dummy_vector = pd.Series([1,None,3,None,7,8])

dummy_vector.isnull()

0    False
1     True
2    False
3     True
4    False
5    False
dtype: bool

In [43]:
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154]),)

## Missing values in Age

In [45]:
titanic_train.loc[missing].head()

Survived  Pclass                           Name     Sex  Age  SibSp  \
5          0  Class3               Moran, Mr. James    male  NaN      0   
17         1  Class2   Williams, Mr. Charles Eugene    male  NaN      0   
19         1  Class3        Masselmani, Mrs. Fatima  female  NaN      0   
26         0  Class3        Emir, Mr. Farred Chehab    male  NaN      0   
28         1  Class3  O'Dwyer, Miss. Ellen "Nellie"  female  NaN      0   

    Parch     Fare Cabin Embarked  
5       0   8.4583     n        Q  
17      0  13.0000     n        S  
19      0   7.2250     n        C  
26      0   7.2250     n        C  
28      0   7.8792     n        Q

In [46]:
titanic_train['Age'][4]

35.0

In [47]:
len(missing[0])

30

In [48]:
index = np.where(titanic_train["Fare"] == max(titanic_train["Fare"]) )

titanic_train.loc[index]

Survived  Pclass                            Name     Sex   Age  SibSp  \
27         0  Class1  Fortune, Mr. Charles Alexander    male  19.0      3   
88         1  Class1      Fortune, Miss. Mabel Helen  female  23.0      3   

    Parch   Fare Cabin Embarked  
27      2  263.0     C        S  
88      2  263.0     C        S

In [50]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]

most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))

titanic_train.loc[most_family]

Survived  Pclass                                Name     Sex   Age  SibSp  \
59         0  Class3  Goodwin, Master. William Frederick    male  11.0      5   
71         0  Class3          Goodwin, Miss. Lillian Amy  female  16.0      5   

    Parch  Fare Cabin Embarked  Family  
59      2  46.9     n        S       7  
71      2  46.9     n        S       7

In [51]:
import numpy as np
import pandas as pd

labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)

Labels: ['a', 'b', 'c']
My data: [10, 20, 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}


In [52]:
k=pd.Series(data=my_data, index=labels) 
k

a    10
b    20
c    30
dtype: int64

In [53]:
#k['a']
k[0]

10

In [54]:
print ("\nHolding numerical data\n",'-'*25, sep='')
print(pd.Series(arr))



Holding numerical data
-------------------------
0    10
1    20
2    30
dtype: int64


In [55]:
print ("\nHolding text labels\n",'-'*20, sep='')
print(pd.Series(labels))



Holding text labels
--------------------
0    a
1    b
2    c
dtype: object


In [56]:
from numpy.random import randn as rn
np.random.seed(101)
matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe data frame looks like\n",'-'*45, sep='')
print(df)


The data frame looks like
---------------------------------------------
          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [57]:
print("\nThe 'X' column\n",'-'*25, sep='')
print(df['X'])


The 'X' column
-------------------------
A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64


In [58]:
print("\nType of the column: ", type(df['X']), sep='')
print("\nThe 'X' and 'Z' columns indexed by passing a list\n",'-'*55, sep='')
print(df[['X','Z']])


Type of the column: <class 'pandas.core.series.Series'>

The 'X' and 'Z' columns indexed by passing a list
-------------------------------------------------------
          X         Z
A  0.628133  0.503826
B -0.319318  0.605965
C  0.740122 -0.589001
D -0.758872  0.955057
E  1.978757  0.683509


In [59]:
print("\nType of the pair of columns: ", type(df[['X','Z']]), sep='')
print ("\nSo, for more than one column, the object turns into a DataFrame")


Type of the pair of columns: <class 'pandas.core.frame.DataFrame'>

So, for more than one column, the object turns into a DataFrame


In [60]:
print("\nThe 'X' column accessed by DOT method (NOT recommended)\n",'-'*55, sep='')
print(df.X)


The 'X' column accessed by DOT method (NOT recommended)
-------------------------------------------------------
A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64


In [70]:
print("\nA column is created by assigning it in relation to an existing column\n",'-'*75, sep='')
df['New'] = df['X']+df['Z']
df['New (Sum of X and Z)'] = df['X']+df['Z']
print(df)



A column is created by assigning it in relation to an existing column
---------------------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
A  2.706850  0.628133  0.907969  0.503826  1.131958              1.131958
B  0.651118 -0.319318 -0.848077  0.605965  0.286647              0.286647
C -2.018168  0.740122  0.528813 -0.589001  0.151122              0.151122
D  0.188695 -0.758872 -0.933237  0.955057  0.196184              0.196184
E  0.190794  1.978757  2.605967  0.683509  2.662266              2.662266


In [71]:
print("\nA column is dropped by using df.drop() method\n",'-'*55, sep='')
df = df.drop('New', axis=1) # Notice the axis=1 option, axis = 0 is default, so one has to change it to 1
print(df)



A column is dropped by using df.drop() method
-------------------------------------------------------
          W         X         Y         Z  New (Sum of X and Z)
A  2.706850  0.628133  0.907969  0.503826              1.131958
B  0.651118 -0.319318 -0.848077  0.605965              0.286647
C -2.018168  0.740122  0.528813 -0.589001              0.151122
D  0.188695 -0.758872 -0.933237  0.955057              0.196184
E  0.190794  1.978757  2.605967  0.683509              2.662266


In [66]:
df1=df.drop('A')
print("\nA row (index) is dropped by using df.drop() method and axis=0\n",'-'*65, sep='')
print(df1)



A row (index) is dropped by using df.drop() method and axis=0
-----------------------------------------------------------------
          W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [72]:
print("\nAn in-place change can be done by making inplace=True in the drop method\n",'-'*75, sep='')
df.drop('New (Sum of X and Z)', axis=1, inplace=True)
print(df)


An in-place change can be done by making inplace=True in the drop method
---------------------------------------------------------------------------
          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [0]:
### Selecting/indexing Rows
#* Label-based 'loc' method
#* Index (numeric) 'iloc' method

In [74]:
print("\nLabel-based 'loc' method can be used for selecting row(s)\n",'-'*60, sep='')
print("\nSingle row\n")
print(df.loc['C'])



Label-based 'loc' method can be used for selecting row(s)
------------------------------------------------------------

Single row

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64


In [84]:
print("\nMultiple rows\n")
print(df.loc[['B','C']])
print('*'*80)




Multiple rows

          W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
********************************************************************************


In [86]:
print("\nIndex position based 'iloc' method can be used for selecting row(s)\n",'-'*70, sep='')
print("\nSingle row\n")
print(df.iloc[2])



Index position based 'iloc' method can be used for selecting row(s)
----------------------------------------------------------------------

Single row

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64


In [90]:
print("\nMultiple rows\n")
print(df.iloc[[1,2]])


Multiple rows

          W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001


In [0]:
#### Subsetting DataFrame

In [0]:
np.random.seed(101)
matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)



In [92]:
print("\nThe DatFrame\n",'-'*45, sep='')
print(df)



The DatFrame
---------------------------------------------
          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [94]:
print("\nElement at row 'B' and column 'Y' is\n") 
print(df.loc['B','Y'])#loc[index,column]



Element at row 'B' and column 'Y' is

-0.8480769834036315


In [95]:
K=df.loc['B']
K['Y']

-0.8480769834036315

In [96]:
print("\nSubset comprising of rows B and D, and columns W and Y, is\n")
df.loc[['B','D'],['W','Y']]


Subset comprising of rows B and D, and columns W and Y, is



W         Y
B  0.651118 -0.848077
D  0.188695 -0.933237

In [97]:
print("\nThe DataFrame\n",'-'*45, sep='')
print(df)



The DataFrame
---------------------------------------------
          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [98]:
print("\nBoolean DataFrame(s) where we are checking if the values are greater than 0\n",'-'*75, sep='')
print(df>0)



Boolean DataFrame(s) where we are checking if the values are greater than 0
---------------------------------------------------------------------------
       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True


In [102]:
np.where(df > 0)

(array([0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 4, 4]),
 array([0, 1, 2, 3, 0, 3, 1, 2, 0, 3, 0, 1, 2, 3]))

In [101]:
df[df > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [104]:
print("\n")
print(df.loc[['A','B','C']]>0)




       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False


In [0]:
       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [105]:
booldf = df>0
print("\nDataFrame indexed by boolean dataframe\n",'-'*45, sep='')
print(df[booldf])


DataFrame indexed by boolean dataframe
---------------------------------------------
          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [0]:
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']


In [107]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nA new DataFrame\n",'-'*25, sep='')
print(df)



A new DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [108]:
print("\nRows with Height > 65 inch\n",'-'*35, sep='')
print(df[df['Height']>65])



Rows with Height > 65 inch
-----------------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160


In [0]:
booldf1 = df['Height']>65
booldf2 = df['Weight']>145


In [110]:
print("\nRows with Height > 65 inch and Weight >145 lbs\n",'-'*55, sep='')
print(df[(booldf1) & (booldf2)])



Rows with Height > 65 inch and Weight >145 lbs
-------------------------------------------------------
   Age  Height  Weight
B   42      70     148
D   35      68     160


In [111]:
print("\nDataFrame with only Age and Weight columns whose Height > 65 inch\n",'-'*68, sep='')
print(df[booldf1][['Age','Weight']])


DataFrame with only Age and Weight columns whose Height > 65 inch
--------------------------------------------------------------------
   Age  Weight
A   22     140
B   42     148
D   35     160


In [115]:
df[df['Height']>65][['Age','Weight']]

Age  Weight
A   22     140
B   42     148
D   35     160

In [0]:
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']


In [117]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe DataFrame\n",'-'*25, sep='')
print(df)



The DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [118]:
print("\nAfter resetting index\n",'-'*35, sep='')
print(df.reset_index())



After resetting index
-----------------------------------
  index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152


In [119]:
print("\nAfter resetting index with 'drop' option TRUE\n",'-'*45, sep='')
print(df.reset_index(drop=True))



After resetting index with 'drop' option TRUE
---------------------------------------------
   Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152


In [120]:
print("\nAdding a new column 'Profession'\n",'-'*45, sep='')
df['Profession'] = "Student Teacher Engineer Doctor Nurse".split()
print(df)



Adding a new column 'Profession'
---------------------------------------------
   Age  Height  Weight Profession
A   22      66     140    Student
B   42      70     148    Teacher
C   30      62     125   Engineer
D   35      68     160     Doctor
E   25      62     152      Nurse


In [121]:
print("\nSetting 'Profession' column as index\n",'-'*45, sep='')
print (df.set_index('Profession'))


Setting 'Profession' column as index
---------------------------------------------
            Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152


In [122]:
# importing pandas as pd
import pandas as pd
 
# importing numpy as np
import numpy as np
 
# dictionary of lists
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
 
# creating a dataframe from list
df = pd.DataFrame(dict)
 
# using isnull() function  
df.isnull()

First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [123]:
df.isnull().sum()

First Score     1
Second Score    1
Third Score     1
dtype: int64

In [124]:
df.fillna(0)

First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [125]:
df

First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [126]:
df.dropna()

First Score  Second Score  Third Score
1         90.0          45.0         40.0

In [127]:
df.columns

Index(['First Score', 'Second Score', 'Third Score'], dtype='object')

In [128]:
df.values

array([[100.,  30.,  nan],
       [ 90.,  45.,  40.],
       [ nan,  56.,  80.],
       [ 95.,  nan,  98.]])

In [129]:
df['First Score'].unique()

array([100.,  90.,  nan,  95.])

In [130]:
df['First Score'].nunique()

3

In [131]:
df['First Score'].value_counts()

95.0     1
90.0     1
100.0    1
Name: First Score, dtype: int64